# Generated by Django 5.2.3 on 2025-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('file_path', models.CharField(max_length=500)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
